apiVersion: v1
kind: Pod
metadata:
  name: sol-rpc-wrapper-pod
  labels:
    team: smart-contracts
spec:
  containers:
  - name: sol-rpc-wrapper
    image: resolcuser/sol-rpc-wrapper:1.0.0
    ports:
    - containerPort: 3000
    resources:
      requests:
        cpu: "8"
        memory: "8Gi"
      limits:
        cpu: "16"
        memory: "16Gi"
