apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter
data:
  config.yaml: |
    rules:
      - seriesQuery: '{__name__="http_request_errors_total", namespace!="",pod!="", status="429"}'
        resources:
          overrides:
            namespace: {resource: "namespace"}
            pod: {resource: "pod"}
        name:
          matches: "^(.*)_total"
          as: "${1}_busy_rate"
        metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[15s])) by (<<.GroupBy>>)'