apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: revive-remix-backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: revive-remix-backend 
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: requests_queue_avg_length  # Metric name configured in the Prometheus Adapter
      target:
        type: AverageValue
        averageValue: "12"  # Scaling threshold
