apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: revive-remix-backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: revive-remix-backend 
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_request_errors_busy_rate  # Metric name configured in the Prometheus Adapter
      target:
        type: AverageValue
        averageValue: "100m"  # Scaling threshold
