apiVersion: v1
kind: Pod
metadata:
  name: revive-remix-backend-pod
  labels:
    team: smart-contracts
spec:
  containers:
  - name: revive-remix-backend
    image: paritytech/revive-remix-backend:1.3.4
    ports:
    - containerPort: 3000
    resources:
      requests:
        cpu: "8"
        memory: "8Gi"
      limits:
        cpu: "12"
        memory: "12Gi"
    env:
    - name: CPU_REQUEST
      valueFrom:
        resourceFieldRef:
          containerName: revive-remix-backend
          resource: requests.cpu
